from typing import Protocol
from app.schemas import HashedPassword


class PasswordHasherProtocol(Protocol):
    def generate_hash(self, raw_password: str) -> HashedPassword: ...

    def verify_hash(self, raw_password: str, hashed_password: str) -> bool: ...
    

class TokenServiceProtocol(Protocol):
    def create_access_token(self, data: dict, expiration_time_minutes: float = 15) -> str: ...

    def create_refresh_token(self, data: dict, expiration_time_days: float = 7) -> str: ...

    def verify_token(self, token: str, expected_type: str) -> str: ...
