from typing import Protocol
from app.schemas import HashedPassword


class PasswordHasherProtocol(Protocol):
    def generate_hash(self, raw_password: str) -> HashedPassword: ...

    def verify_hash(self, raw_password: str, hashed_password: str) -> bool: ...
    

class TokenServiceProtocol(Protocol):
    def create_access_token(self, data: dict) -> str: ...

    def create_refresh_token(self, data: dict) -> str: ...

    def verify_token(self, token: str, expected_type: str) -> str: ...
