name: CI

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Dependencies
        run: uv sync

      - name: Run Tests
        env:
          TOKEN_EXPIRATION_MINUTES: ${{ secrets.TOKEN_EXPIRATION_MINUTES }} 
          SECRET_KEY: ${{ secrets.SECRET_KEY }} 
          HASHING_ALGORITHM: ${{ secrets.HASHING_ALGORITHM }} 
          SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }} 
        run: uv run pytest --cov=app

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Docker Image
        run: docker image build -t my-api .
